### ISSUE TITLE
Migrate flows to use query parameter responses store

### ISSUE THREAD

**Issue by theseanything** [alphagov/smart-answers#5552]
We recently introduced the ability to use query parameters as a response store. We should migrate the existing flows that use the URL path to store user responses to use query parameters. This will help remove redundant code and make the functionality of Smart Answer consistent.

To help prevent user interruption during the deployment of updates flows this PR implements a automatic redirect from path based to query parameter URLs. https://github.com/alphagov/smart-answers/pull/5648

---
### Flows to migrate:

- [ ] addition-commodity-code #5545
- [ ] all-smart-answer-questions
- [ ] am-i-getting-minimum-wage
- [ ] business-coronavirus-support-finder
- [ ] calculate-agricultural-holiday-entitlement
- [ ] calculate-employee-redundancy-pay
- [ ] calculate-married-couples-allowance
- [ ] calculate-statutory-sick-pay
- [ ] calculate-your-holiday-entitlement
- [ ] calculate-your-redundancy-pay
- [ ] check-uk-visa
- [ ] child-benefit-tax-calculator
- [ ] childcare-costs-for-tax-credits
- [ ] estimate-self-assessment-penalties
- [ ] help-if-you-are-arrested-abroad
- [ ] inherits-someone-dies-without-will
- [ ] marriage-abroad
- [ ] maternity-paternity-calculator
- [ ] maternity-paternity-pay-leave
- [ ] minimum-wage-calculator-employers
- [ ] part-year-profit-tax-credits
- [ ] plan-adoption-leave
- [ ] register-a-birth
- [ ] register-a-death
- [ ] report-a-lost-or-stolen-passport #5554
- [ ] simplified-expenses-checker
- [ ] state-pension-age
- [ ] state-pension-through-partner
- [ ] student-finance-calculator
- [ ] towing-rules
- [ ] uk-benefits-abroad
- [ ] vat-payment-deadlines #5555
